### PR TITLE
Windows fixes

### PR DESCRIPTION
**Pull request by dscho**
I [finally got Git Bash to accept the Windows Store version of Python](https://github.com/msys2/msys2-runtime/pull/27), so naturally I wanted to verify that the test suite works, but that was not so, funnily enough.

With these two fixes, I can run t9391 successfully in Git for Windows v2.31.1.

### CODE REVIEW

**Comment by dscho** [comment]
Hrm. I see this failure:

```
[...]
2021-03-30T20:56:22.6773660Z ++ git add foobar.c
2021-03-30T20:56:22.7032750Z warning: LF will be replaced by CRLF in foobar.c.
2021-03-30T20:56:22.7033830Z The file will have its original line endings in your working directory
2021-03-30T20:56:22.7104433Z ++ test_tick
2021-03-30T20:56:22.7105665Z ++ test -z set
2021-03-30T20:56:22.7112391Z ++ test_tick=1112912293
2021-03-30T20:56:22.7113145Z ++ GIT_COMMITTER_DATE='1112912293 -0700'
2021-03-30T20:56:22.7113744Z ++ GIT_AUTHOR_DATE='1112912293 -0700'
2021-03-30T20:56:22.7114516Z ++ export GIT_COMMITTER_DATE GIT_AUTHOR_DATE
2021-03-30T20:56:22.7115444Z ++ git commit -m 'Brain damage'
2021-03-30T20:56:22.7538070Z [master 7d3b5dd] Brain damage
2021-03-30T20:56:22.7539248Z  Author: A U Thor <author@example.com>
2021-03-30T20:56:22.7539879Z  1 file changed, 1 insertion(+)
2021-03-30T20:56:22.7540479Z  create mode 100644 foobar.c
2021-03-30T20:56:22.7649100Z ++ cd print_progress
2021-03-30T20:56:22.7729653Z +++ git rev-parse --verify master
2021-03-30T20:56:22.8006045Z ++ MASTER=7d3b5dddd77d25eb401a95ccbe1a90491a6af781
2021-03-30T20:56:22.8008263Z ++ /d/a/git-filter-repo/git-filter-repo/t/t9391/print_progress.py . new
2021-03-30T20:56:22.9830727Z b'.' does not appear to be a valid git repository
2021-03-30T20:56:22.9990926Z error: last command exited with $?=1
2021-03-30T20:56:22.9991907Z not ok 3 - print_progress.py
2021-03-30T20:56:23.0281824Z ++ setup rename_master_to_develop
2021-03-30T20:56:23.0282198Z #	
2021-03-30T20:56:23.0284876Z #		setup print_progress &&
2021-03-30T20:56:23.0285599Z ++ git init rename_master_to_develop
2021-03-30T20:56:23.0286086Z #		(
2021-03-30T20:56:23.0286587Z #			cd print_progress &&
2021-03-30T20:56:23.0287322Z #			MASTER=$(git rev-parse --verify master) &&
2021-03-30T20:56:23.0288063Z #			$TEST_DIRECTORY/t9391/print_progress.py . new &&
2021-03-30T20:56:23.0288719Z #			test $MASTER = $(git rev-parse --verify refs/heads/master)
2021-03-30T20:56:23.0289214Z #		)
2021-03-30T20:56:23.0289528Z #	
```

But then, I see the same failure in `main`... What gives?

**Comment by newren** [comment]
Interesting.  Not sure why this never triggered problems before, but is it possible that the program "wc" doesn't exist on some Windows boxes like it does on Linux & Mac?  Maybe it exists for you, and existed at some point in the past under GitHub Actions, but doesn't exist within whatever current GitHub Actions environment for Windows provides anymore?

Anyway, the patches look good to me.  I'll see if I can play with the Windows tests and that suboptimal error message a bit and get it fixed up, then merge these changes.

**Comment by newren** [comment]
Merged...but I'm an evil maintainer and I rewrote history for some commits from a few months ago (I'm hiding behind the excuse that this is the filter-repo project so folks should be able to handle history rewrites, or something like that).  So, I had to rebase your patches and GitHub doesn't detect it as merged.  But it is merged.

Thanks for the fixes!

**Comment by dscho** [comment]
Thank you!

**Comment by alisenajafari1-dot** [comment]
Can you help me

**Pull request closed without merging**
