### PR TITLE
t9394: Mask compressed size for comparison.

### PR DESCRIPTION
**Pull request by sebastianas**
Instead of trying to expect a static difference of the compressed content between zlib and zlib-ng mask the compressed size and ignore it while comparing.

Fixes: #614

### CODE REVIEW

**Review by newren — CHANGES_REQUESTED** [review]
Ah, don't even try to compare packed sizes at all?  That's kind of a big hammer, I was thinking of putting in some kind of relative tolerance, but it's certainly easier this way.  Maybe that's good enough.

Two things that we'd need fixed, though:
  * You had a different author than committer on your commit.  They either need to be the same, or we need a signoff from both identities.
  * Please drop the "Fixes: #614" trailer.  I'm still trying to make sure the history would make sense for being merged into git, and that trailer wouldn't make sense.

**Comment by sebastianas** [comment]
On 2024-11-30 20:10:21 [-0800], Elijah Newren wrote:
> Ah, don't even try to compare packed sizes at all?  That's kind of a
> big hammer, I was thinking of putting in some kind of relative
> tolerance, but it's certainly easier this way.  Maybe that's good
> enough.

You have cmp in there and I was nore sure how to add something that
accepts a range of values in a specific column. Also the compressed
values are larger than the original - not something one expects :)

> Two things that we'd need fixed, though:
>   * You had a different author than committer on your commit.  They either need to be the same, or we need a signoff from both identities.
>   * Please drop the "Fixes: #614" trailer.  I'm still trying to make sure the history would make sense for being merged into git, and that trailer wouldn't make sense.

Fixed both.

**Comment by newren** [comment]
> You have cmp in there and I was nore sure how to add something that accepts a range of values in a specific column. Also the compressed values are larger than the original - not something one expects :)

Oh, there's no builtin tooling for trying to do range or tolerance comparison.  It'd very much be a case of writing something a script or something for the testsuite specifically for that purpose.

> Fixed both.

Thanks.  Unfortunately, it appears the tests fail on mac, I believe due to the use of `\s` being passed to sed (see https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed).

**Comment by sebastianas** [comment]
On 2024-12-02 00:50:55 [-0800], Elijah Newren wrote:
> Thanks.  Unfortunately, it appears the tests fail on mac, I believe
> due to the use of `\s` being passed to sed (see
> https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed).

Thank you for the hint. I replaced it with [[:space:]] and keep my
fingers crossed :)

Sebastian

**Review by newren — APPROVED** [review]

**Comment by newren** [comment]
Thanks!

**Pull request merged**
