### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by katef**

### CODE REVIEW

**Comment by newren** [comment]
Awesome, thanks for catching this and reporting it.  As per the contribution guidelines, can you make the commit message include the area, e.g. "git-filter-repo.txt: fix typo", and also include your Signed-off-by (`git commit --amend -s` should add the signed off by automatically, and allow you to edit the commit message to add the area).

**Comment by katef** [comment]
Ah yes, of course. I didn't even look at the contribution guidelines, sorry!

**Comment by newren** [comment]
Thanks!

**Comment by katef** [comment]
Thanks for the wonderful utility :)

**Pull request merged**
