### PR TITLE
Fixes for #12

### PR DESCRIPTION
**Pull request by BatmanAoD**
Create 'docs' branch if necessary; create Documentation subdirs

Addresses concerns in #12

### CODE REVIEW

**Comment by newren** [comment]
Hi, thanks for the fixes.  I really need to get some contribution guidelines up.

This turns out to be a duplicate of #10; most of my comments there also apply here.  Since @benblo filed first, I'll merge his changes if he updates them in the next few days; if not, and you update yours, then I'll go ahead and merge yours.

**Comment by newren** [comment]
Oh, one more thing.  I'd prefer to avoid things like "Resolves #12", as it makes the history depend on an external service that isn't obvious.  Commit messages should explain the problem in sufficient detail to understand; if that isn't possible for some reason or you want to be able to point users at additional discussion, please use a full URL.

**Comment by BatmanAoD** [comment]
Oops, I did briefly search open issues but didn't see that one. I'll close this. 

"Resolves" only modifies the issue thread, not the commit history, correct?

**Comment by newren** [comment]
Sorry about "Resolves"; I for some reason thought it was included in the commit message rather than just the PR summary.  Having it in the PR summary would be fine since that'd be GitHub specific anyway.

**Comment by BatmanAoD** [comment]
Fair enough; that feature does feel pretty "magic" so I wanted to be sure I understood its effect as well.

**Pull request closed without merging**
