### PR TITLE
docs(collection): update docs around collecting and installing doc files

### LINKED ISSUE #140: No git-repo-filter.html file in root
In the INSTALL.md instruction there is a reference to git-filter-repo.html (and to git-filter-repo.1) both are **not found** in the (root of) the repository.

### PR DESCRIPTION
**Pull request by joshsleeper**
redo of #149 because apparently squashing the commits when the previous PR was closed caused it to lose track of the source commits and branch, so I couldn't re-open it 😑

sorry for the long delay, I totally lost track of this PR until you closed it just recently lol

re: your comments here https://github.com/newren/git-filter-repo/pull/149#pullrequestreview-501364636:

- [x] Please add a Signed-off-by tag to the commit message as per contributing guidelines
- [ ] Please use a real email address; I'm guessing GitHub put @users.noreply.github.com in there from inline editing or something.
    - at the time you're right, it was because I'd done the edits through the github web app.
    that said github now supports a privacy feature to help folks avoid committing their real email address in github, which is something I quite like from a privacy standpoint.
    if you're willing, I'd really appreciate allowing me to stick with using the noreply address in the `Signed-off-by:` tag unless that's truly problematic for some reason
    - image

- [x] Please remove the whitespace error(s) (visible from 'git log -p --check')
    - done, thanks for the catch! I hate that github's web editor doesn't remove trailing whitespace by default
- [x] Please squash the two commits together to make the history clean.

## original PR message below

simple update to clarify how to obtain the doc files

closes #140 (which is where I learned what I needed to do~)

### CODE REVIEW

**Comment by joshsleeper** [comment]
ugh, I am just having a moment here with the commit target and history, I'll fix it sorry...

**Comment by joshsleeper** [comment]
well now the changes are half the size since you or someone else slipped in equivalent changes in the bottom half of the file haha. oh well, up to you if you still like the remaining notes or not.

**Comment by joshsleeper** [comment]
I'll be honest, I don't understand the test failure at all. heck, I can't even _find_ the failure in the output.

**Review by newren — CHANGES_REQUESTED** [review]
Sorry for taking a long time to get back to you.  I kept mulling over the Signed-off-by thing.  I understand the desire to be anonymous, but the authorship record feels important to me.  I know that email addresses are not necessarily forever, but based of the Linux kernel wording about Signed-off-by (where this requirement was original adopted from) which says that "(sorry, no pseudonyms or anonymous contributions.)" I think I need to disallow the @users.noreply.github.com sign offs.

I understand if that's too much to ask (or I took too long decide here) and we need to just close the pull request.  Whatever you decide, thanks for taking the time to contribute.

**Comment by joshsleeper** [comment]
eh, at this point the PR changes are small enough that I'm just not that compelled I guess haha.

I don't like giving out my personal email where I don't have to, and don't have desire to maintain a separate email _exclusively_ for commits, so I'll just close out the PR instead.

thanks for giving it some genuine consideration and a detailed response, regardless of delay :wink:

if you feel like the couple of doc lines left in the PR are still worth having, I encourage you to please just add them yourself. after all, I'm more interested in the source changes themselves over my name being attached to them!

**Pull request closed without merging**
