### PR TITLE
Add a GitHub workflow for continuous testing

### PR DESCRIPTION
**Pull request by dscho**
The idea is to fix the tests so that they pass on Windows, and then have a GitHub workflow that runs on every push and Pull Request to ensure that no regressions are introduced on the main three platforms: Windows, macOS and Linux.

### CODE REVIEW

**Comment by dscho** [comment]
@newren I plan on working on this a little bit more. Please note that this PR takes the unrefined work I presented in https://lore.kernel.org/git/nycvar.QRO.7.76.6.2010211630010.56@tvgsbejvaqbjf.bet/ and refines it _a little_ more.

**Comment by dscho** [comment]
TODO: use https://github.com/marketplace/actions/setup-python instead of downloading the full-fledged Git for Windows SDK (which takes ~3m20, quite a bit longer than actually running the tests).

**Comment by dscho** [comment]
@newren while I have your attention... t9390.43 seems to fail for me all the time, even in WSL (i.e. Linux):

```
[...]
++ test_line_count = 5 ../filenames
++ test 3 '!=' 3
+++ wc -l
++ test 6 = 5
++ echo 'test_line_count: line count for ../filenames != 5'
test_line_count: line count for ../filenames != 5
++ cat ../filenames

numbers/medium.num
numbers/small.num
sequence/know
whatever
words/know
++ return 1
error: last command exited with $?=1
not ok 43 - --strip-blobs-with-ids
```

Is this test passing for you?

**Comment by dscho** [comment]
> Is this test passing for you?

Oh wait, it passes for me on Linux with v2.29.0. Let me investigate.

**Comment by dscho** [comment]
Ahhh! 2ca6e362bdbe7e938092e192ee68fde823c33c48 is the "culprit" ;-)

**Comment by newren** [comment]
Ah, that '&&' was masking a bug in the testcase.  Not sure how it got in there, but digging through it, the correct count is 6.  The failure is in part due to the file named 'mercurial'; it was introduced in an "evil" merge and didn't exist in either parent.  But my method for checking which files existed was kinda lame.

In addition to adding the '&&' and changing the expected count to 6, I should probably add a
```
		test_must_fail git rev-parse HEAD~4:mercurial &&
```
line to the test to ensure the mercurial file was ripped out.

**Comment by dscho** [comment]
Right. I actually managed to fix that, and pinpoint it to the commit that introduced the test case: b6a35f8

**Comment by dscho** [comment]
There you go.

**Comment by dscho** [comment]
@newren would you kindly review this thing? I know, you don't like GitHub's PR UI because it does not let you comment easily on commit messages. Hopefully there is not a lot you need to comment about, though.

**Comment by newren** [comment]
Sweet, thanks @dscho; this is awesome!

**Comment by newren** [comment]
...and thanks for writing such great commit messages, as always.  I learned a couple things about MSYS2 and Windows; I think one of those might be relevant to one of the issues that was filed if I can find it...

**Pull request merged**
